site_name: 6031 Wiki
docs_dir: src
site_dir: docs

# Repository
repo_name: 'eLecCap1taL/6031Wiki'
repo_url: 'https://github.com/eLecCap1taL/6031Wiki'

# Copyright
copyright: 'Copyright &copy; 2025 - 2025 eLecCap1taL'

nav:
  - 简介:
    - 主页: index.md
  - 世家:
    - 主页: shijia/index.md
    - 肖卫 世家:
      - 概述: shijia/xwd/index.md
      - 清北要过半 C9要全面: shijia/xwd/THUHALF-PKU-ALL.md
      - 试卷如矢: shijia/xwd/paper-like-shit.md
    - Doorman 世家: 
      - 概述: shijia/doorman/index.md
      - 非常烂糊: shijia/doorman/lanhu.md
      - 回收: shijia/doorman/recycle.md
      - 孝子食饼: shijia/doorman/story-1.md
      - 食兔疑肉: shijia/doorman/story-2.md
    - 蚂蚁 世家:
      - 概述: shijia/ant/index.md
      - 树全切: shijia/ant/ant-fullcombo.md
    - 佐传 世家:
      - 概述: shijia/zuozhuan/index.md
    - 严神 世家:
      - 概述: shijia/yanshen/index.md


theme:
  name: material
  custom_dir: overrides/

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        
  language: zh

  logo: assets/images/xwd-256.png
  
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'


# Extensions
markdown_extensions:
  # - document-offsets-injection:
      # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  # - toc:
      # permalink: ""
      # slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true